
services:
  - type: web
    name: violetvibes-server
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
  - type: web
    name: violetvibes-client
    env: node
    rootDir: client
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --port 3000
